language: java
jdk:
- oraclejdk8
sudo: false # faster builds
install:
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
after_success:
  - mvn clean test jacoco:report coveralls:report
