language: java
jdk:
- oraclejdk8
sudo: false # faster builds
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report
